### ISSUE TITLE
Laboratory Work #0

### ISSUE THREAD

**Issue by Procentguide2** [OS-IS/ai201-kalarashan#1]

**Comment by Procentguide2** [comment]
![image](https://github.com/user-attachments/assets/4a256de9-1256-41e7-bff3-0da3a245dde0)

**Comment by Procentguide2** [comment]
![image](https://github.com/user-attachments/assets/7f22ac95-c616-4deb-a005-f236cca32cc5)

**Comment by Procentguide2** [comment]
![image](https://github.com/user-attachments/assets/76a00ef1-4dc5-4728-b2cb-d30793813537)

**Comment by Procentguide2** [comment]
![image](https://github.com/user-attachments/assets/98ba5d2b-a09d-4334-b777-b895e002793e)

**Comment by Procentguide2** [comment]
![image](https://github.com/user-attachments/assets/d4223275-fba4-47a6-a872-362fcb4f671a)

**Comment by Procentguide2** [comment]
![image](https://github.com/user-attachments/assets/67bdae7c-7b2d-48b0-baba-d577ada69fc4)

**Comment by Procentguide2** [comment]
![image](https://github.com/user-attachments/assets/0120aba3-a33f-48a2-a3d7-21b90a2aa62a)

**Comment by Procentguide2** [comment]
![image](https://github.com/user-attachments/assets/ebf2ed63-9a19-4908-90ad-e1186aa3bebd)

**Comment by Procentguide2** [comment]
![image](https://github.com/user-attachments/assets/ab8d19b1-6e4a-4f30-abf8-768d0e5889ae)

**Comment by Procentguide2** [comment]
![image](https://github.com/user-attachments/assets/9f2d7c19-42c9-42d7-a991-e0d2ac48f22c)

**Comment by Procentguide2** [comment]
![image](https://github.com/user-attachments/assets/01e94f5c-34b4-4697-88ed-133b0c444172)

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 5 балів.
Дякую
