### ISSUE TITLE
CW5

### ISSUE THREAD

**Issue by Procentguide2** [OS-IS/ai201-kalarashan#13]
Перше завдання:

Початкові умови:
Кількість таблиць = 9 * 3 = 27
Кількість користувачів = 9 * 4 = 36
Кількість груп (ролей) = 9 * 2 = 18
Трудомісткість для DAC:
В моделі DAC (Discretionary Access Control) кожен користувач має право на доступ до певних таблиць. Трудомісткість обчислюється за кількістю перевірок доступу на кожну таблицю для кожного користувача.

Для кожного користувача необхідно перевірити доступ до кожної таблиці.
Трудомісткість для DAC: Кількість користувачів * Кількість таблиць = 36 * 27 = 972
Трудомісткість для RBAC:
В моделі RBAC (Role-Based Access Control) доступ користувачів до таблиць визначається через їх ролі. Для кожного користувача потрібно перевірити його роль і потім доступ до таблиць, що пов’язані з цією роллю.

Кількість ролей = 18
Трудомісткість для RBAC: Кількість користувачів * Кількість ролей = 36 * 18 = 648
Трудомісткість для MAC:
В моделі MAC (Mandatory Access Control) доступ до таблиць визначається за політиками безпеки, і перевірка доступу залежить від рівня конфіденційності або безпеки. Трудомісткість може бути вищою через складність перевірок політик.

Трудомісткість для MAC може бути більш складною в залежності від кількості політик.
Припустимо, для MAC трудомісткість: Кількість користувачів * Кількість таблиць = 36 * 27 = 972
Підсумки для першої умови:
DAC: 972
RBAC: 648
MAC: 972
Висновок:
В умовах, коли кількість користувачів і таблиць не є дуже великою, модель RBAC виглядає найбільш оптимальною з точки зору трудомісткості, оскільки кількість ролей значно менша за кількість користувачів і таблиць.
Перехід на DAC або MAC не є вигідним через вищу трудомісткість для цих моделей у порівнянні з RBAC.

Зміна умов:
Кількість користувачів: 36 * 2 = 72
Кількість ролей: 18 / 2 = 9
Трудомісткість для DAC:
Трудомісткість для DAC = 72 * 27 = 1944

Трудомісткість для RBAC:
Трудомісткість для RBAC = 72 * 9 = 648

Трудомісткість для MAC:
Трудомісткість для MAC = 72 * 27 = 1944

Підсумки для нових умов:
DAC: 1944
RBAC: 648
MAC: 1944
Висновок:
В нових умовах, де кількість користувачів значно зросла, модель RBAC залишається найефективнішою через зменшення кількості ролей у порівнянні з DAC і MAC.
Перехід на DAC або MAC призведе до значного збільшення трудомісткості, тому збереження RBAC є оптимальним варіантом.

**Comment by Procentguide2** [comment]
Друге завдання:

Файли/Таблиці БД:
Таблиці для зберігання даних про користувачів, білетів, сеансів, фільмів.

Користувачі:
Споживачі які люблять дивитися кіно у кінотеатрах

Групи (ролі):
незареєстрований користувач, зареєстрований користувач, адміністрація

Поточна модель керування доступом
Модель: DAC
Реалізація: Користувачам надаються дозволи на основі унікальних ідентифікаторів.

Рекомендації для масштабування
Перехід на RBAC забезпечить спрощення, оскільки користувачі можуть бути згруповані за ролями, що зменшує потребу в налаштуванні доступу для кожного нового користувача.

**Comment by oleksandrblazhko** [comment]
5
