### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by Procentguide2** [OS-IS/ai201-kalarashan#5]
Reliability - виконано
 Availability - виконано
 Security - використовується шифрування даних, ведуться логи - виконано
 Maintainability - використовуються різні модулі для обслуговування програмного забезпечення(модуль апі, модуль бази даних, та інше) - виконано
 Portability -  використана перевірена портативна мова Java - виконано

**Comment by oleksandrblazhko** [comment]
2 бали
